name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake make git libcurl4-openssl-dev libboost-dev libqt5charts5-dev libmlpack-dev libensmallen-dev libarmadillo-dev libstb-dev pybind11-dev graphviz libgraphviz-dev libqt5svg5-dev qtwebengine5-dev build-essential python3-sympy
        sudo apt install -y libgoogle-glog-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev
        git clone --recursive https://ceres-solver.googlesource.com/ceres-solver
        cd ceres-solver
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=OFF
        make -j$(nproc)
        sudo make install
        cd ../..
        git clone https://github.com/Julien-Livet/Sym.git
        cd Sym
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: |
        cd build
        cmake -DNOISE_PERCENTAGE=0.0 ..
        make -j$(nproc)
        sudo make install

    - name: Run tests
      run: ctest -j$(nproc) --test-dir build --output-on-failure
